-- =====================================================================
-- S.S.E Industries website — Supabase setup
-- Run this whole file ONCE in Supabase → SQL Editor → New query → Run.
-- Before running, change the admin email at the bottom (section 6).
-- =====================================================================

create extension if not exists pgcrypto;

-- 1. TABLES -------------------------------------------------------------
create table if not exists public.items (
  id          text primary key default gen_random_uuid()::text,
  collection  text not null,
  data        jsonb not null default '{}'::jsonb,
  sort_order  int  not null default 0,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists items_collection_idx on public.items (collection, sort_order);

create table if not exists public.site_content (
  key        text primary key,
  value      jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.enquiries (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  company      text default '',
  email        text default '',
  phone        text not null,
  enquiry_type text default '',
  product      text default '',
  message      text default '',
  source       text default 'website',
  page_url     text default '',
  status       text not null default 'new',
  notes        text default '',
  created_at   timestamptz not null default now()
);
create index if not exists enquiries_created_idx on public.enquiries (created_at desc);

create table if not exists public.admin_users (
  email      text primary key,
  role       text not null default 'editor' check (role in ('super_admin','editor')),
  created_at timestamptz not null default now()
);

-- 2. HELPER FUNCTIONS ---------------------------------------------------
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users a where lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', '')));
$$;

create or replace function public.is_super_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users a where lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', '')) and a.role = 'super_admin');
$$;

-- 3. ROW LEVEL SECURITY -------------------------------------------------
alter table public.items        enable row level security;
alter table public.site_content enable row level security;
alter table public.enquiries    enable row level security;
alter table public.admin_users  enable row level security;

drop policy if exists "items public read"  on public.items;
drop policy if exists "items admin write"  on public.items;
create policy "items public read" on public.items for select using (is_active or public.is_admin());
create policy "items admin write" on public.items for all using (public.is_admin()) with check (public.is_admin());
-- visitors may submit a testimonial; it stays hidden until an admin approves it
drop policy if exists "items public testimonial submit" on public.items;
create policy "items public testimonial submit" on public.items for insert to anon, authenticated
  with check (collection = 'testimonials' and is_active = false and (data ->> 'submitted') = 'true' and length(coalesce(data ->> 'message', '')) between 5 and 1500);

drop policy if exists "content public read" on public.site_content;
drop policy if exists "content admin write" on public.site_content;
create policy "content public read" on public.site_content for select using (true);
create policy "content admin write" on public.site_content for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "enquiries public insert" on public.enquiries;
drop policy if exists "enquiries admin read"    on public.enquiries;
drop policy if exists "enquiries admin update"  on public.enquiries;
drop policy if exists "enquiries admin delete"  on public.enquiries;
create policy "enquiries public insert" on public.enquiries for insert to anon, authenticated
  with check (status = 'new' and length(name) between 1 and 200 and length(phone) between 6 and 30 and length(coalesce(message,'')) <= 2000);
create policy "enquiries admin read"   on public.enquiries for select using (public.is_admin());
create policy "enquiries admin update" on public.enquiries for update using (public.is_admin()) with check (public.is_admin());
create policy "enquiries admin delete" on public.enquiries for delete using (public.is_admin());

drop policy if exists "admins read"        on public.admin_users;
drop policy if exists "super admin manage" on public.admin_users;
create policy "admins read" on public.admin_users for select
  using (public.is_admin() or lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));
create policy "super admin manage" on public.admin_users for all using (public.is_super_admin()) with check (public.is_super_admin());

-- 4. STORAGE (public bucket for images / PDFs) --------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values ('media', 'media', true, 52428800)
on conflict (id) do update set public = true, file_size_limit = 52428800;

drop policy if exists "media public read"   on storage.objects;
drop policy if exists "media admin insert"  on storage.objects;
drop policy if exists "media admin update"  on storage.objects;
drop policy if exists "media admin delete"  on storage.objects;
create policy "media public read"  on storage.objects for select using (bucket_id = 'media');
create policy "media admin insert" on storage.objects for insert to authenticated with check (bucket_id = 'media' and public.is_admin());
create policy "media admin update" on storage.objects for update to authenticated using (bucket_id = 'media' and public.is_admin());
create policy "media admin delete" on storage.objects for delete to authenticated using (bucket_id = 'media' and public.is_admin());

-- 5. DEFAULT CONTENT (only inserted if the tables are empty) ------------
do $$ begin
if not exists (select 1 from public.site_content) then
  insert into public.site_content (key, value) values ('settings', '{"company_name":"S.S.E Industries","brand_word":"INDUSTRIES","tagline":"The Future of the Rice","logo":"/images/logo-mark.png","logo_full":"/images/logo.png","favicon":"/favicon.png","admin_bg":"/images/hero-home.jpg","phone":"+91 9945437725","phone_alt":"","whatsapp":"919945437725","whatsapp_default_message":"Hello S.S.E Industries, I would like to know more about your rice mill solutions.","whatsapp_after_form":true,"show_whatsapp_float":true,"show_call_float":true,"email":"sseindustries6@gmail.com","address":"#121, NH Road 766, Near Union Bank of India, Yedehalli, Sagara, Shivamogga Dist. Bangalore - 577412","working_hours":"Mon - Sat : 9:00 AM - 6:00 PM","working_note":"(Sunday Holiday)","map_embed_url":"https://maps.google.com/maps?q=Yedehalli%2C%20Sagara%2C%20Shivamogga%2C%20Karnataka&z=13&output=embed","map_link":"https://www.google.com/maps/search/?api=1&query=Yedehalli+Sagara+Shivamogga+Karnataka","linkedin":"#","youtube":"#","facebook":"#","instagram":"","footer_about":"Manufacturers of rice mill blowers, bunkers, erection & material handling systems and complete rice mill solutions across India.","footer_quote":"Engineering Today for a Better Tomorrow","footer_bottom":"Manufacturing a Stronger Agricultural Tomorrow.","copyright":"© {year} S.S.E Industries. All Rights Reserved.","header_cta_text":"Get a Quote","seo_title":"S.S.E Industries | Rice Mill Blowers, Bunkers & Complete Rice Mill Solutions","seo_description":"S.S.E Industries – manufacturers of rice mill blowers, bunkers & hoppers, erection & material handling and complete rice mill solutions across India.","announcement":"","brochure_url":"","credit_text":"Designed & Developed by Nikki Technologies","credit_url":"https://nikkitechnologies.com"}'::jsonb);
  insert into public.site_content (key, value) values ('common', '{"stats":[{"icon":"Factory","value":"100+","label":"Projects Completed"},{"icon":"Users","value":"50+","label":"Happy Customers"},{"icon":"Settings","value":"10+","label":"Years Experience"},{"icon":"MapPin","value":"Pan-India","label":"Service Network"}],"why":[{"icon":"Gem","title":"Proven Expertise","text":"Deep understanding of rice milling needs"},{"icon":"Settings","title":"Custom Solutions","text":"Tailor-made design and fabrication"},{"icon":"ShieldCheck","title":"Superior Quality","text":"Durable and high-performance equipment"},{"icon":"Leaf","title":"Energy Efficient","text":"Designed for lower power consumption"},{"icon":"Headphones","title":"End-to-End Support","text":"From consultation to after-sales service"}],"cta_title":"Let''s Build a More Productive Tomorrow","cta_text":"Get the right rice mill equipment for your business. Our team is ready to support you with the best solutions.","cta_button":"Request a Quote","cta_image":"/images/ind-1.jpg"}'::jsonb);
  insert into public.site_content (key, value) values ('home', '{"hero_badges":[{"icon":"Gauge","label":"High Performance"},{"icon":"Settings","label":"Durable Design"},{"icon":"Leaf","label":"Energy Efficient"},{"icon":"Handshake","label":"Trusted Across India"}],"hero_side_title":"Better Grains\nBrighter Tomorrows","hero_side_text":"Innovative Solutions for a Stronger Agricultural Tomorrow","hero_corner_text":"From Field\nto a Brighter World","strip":[{"icon":"Wrench","title":"Custom Fabrication","text":"As per your requirement"},{"icon":"Truck","title":"On-Time Delivery","text":"Reliable & Efficient"},{"icon":"MapPin","title":"Pan-India Service","text":"Installation & Support"},{"icon":"Users","title":"Customer Satisfaction","text":"Our First Priority"}],"products_eyebrow":"Our Products","products_title":"Rice Mill Machinery & Equipment","about_eyebrow":"About S.S.E Industries","about_title":"Your Trusted Partner in Rice Mill Engineering","about_text":"S.S.E Industries is a leading manufacturer of rice mill blowers, bunkers, and material handling systems. We deliver high-quality, durable and efficient solutions to modern rice mills across India. With a focus on innovation and customer satisfaction, we help our clients achieve better productivity, lower maintenance and long-term performance.","about_image":"/images/about-factory.jpg","about_button":"Know More About Us","about_image2":"/images/plant-3.jpg","about_points":["In-house design & fabrication","Experienced erection team","Energy-efficient equipment","After-sales service & spares"],"band_eyebrow":"Complete Rice Mill Solutions","band_title":"From Paddy Intake to Final Packing — One Trusted Partner","band_text":"Blowers, bunkers, elevators, conveyors, dryers and complete plant erection, designed and built to match your capacity and layout.","band_image":"/images/hero-industries.jpg","band_button":"Discuss Your Project","process_eyebrow":"Our Process","process_title":"From Concept to Commissioning","process":[{"title":"Consultation","text":"Understanding your needs"},{"title":"Design & Engineering","text":"Customized solutions with precision"},{"title":"Manufacturing","text":"High quality fabrication"},{"title":"Erection & Installation","text":"On-site support by expert team"},{"title":"After-Sales Service","text":"Reliable long-term support"}],"industries_eyebrow":"Industries We Serve","industries_title":"Applications Across the Rice Value Chain","projects_eyebrow":"Our Projects","projects_title":"Real Solutions. Real Impact.","why_title":"Why Choose S.S.E Industries?","video_url":"","video_image":"/images/gal-8.jpg","video_title":"Watch Our Journey","video_sub":"See how we build a better tomorrow","testimonials_title":"What Our Clients Say","clients_strip_title":"Trusted by Rice Mills Across India","faq_title":"Frequently Asked Questions"}'::jsonb);
  insert into public.site_content (key, value) values ('about', '{"hero_eyebrow":"About Us","hero_title":"About","hero_highlight":"S.S.E Industries","hero_subtitle":"Engineering Solutions for a Stronger Agricultural Tomorrow","hero_text":"S.S.E Industries is a leading manufacturer of rice mill blowers, bunkers, material handling systems and custom rice mill equipment. We are committed to delivering high-quality, durable and energy-efficient solutions that help rice millers achieve better productivity and profitability.","hero_image":"/images/about-factory.jpg","hero_side_text":"Rice Mill Solutions\nfor a Brighter Tomorrow","hero_badges":[{"icon":"Settings","label":"Quality Products"},{"icon":"Users","label":"Customer Focus"},{"icon":"Leaf","label":"Sustainable Growth"}],"story_title":"Our Story","story_text":"S.S.E Industries was established with a clear vision to support the rice milling industry with reliable, innovative and cost-effective equipment. Over the years, we have earned the trust of clients across India by maintaining a strong focus on engineering excellence, timely delivery and customer satisfaction.","story_text2":"From small rice mills to large-scale processing plants, our solutions are designed to meet the evolving needs of the agricultural sector.","mission":"To provide world-class rice mill equipment with innovative designs, superior quality and unmatched service, enabling our customers to grow sustainably.","vision":"To be a trusted global partner in rice milling solutions, recognized for our engineering excellence, customer-centric approach and contribution to a stronger agricultural future.","values":["Quality & Reliability","Customer Satisfaction","Innovation & Continuous Improvement","Integrity & Transparency","Sustainable Solutions"],"banner_text":"Supporting Food Security Through Better Rice Processing","banner_image":"/images/ind-1.jpg","video_url":"","video_image":"/images/gal-8.jpg","video_title":"Watch Our Journey","video_sub":"See how we build a better tomorrow"}'::jsonb);
  insert into public.site_content (key, value) values ('products_page', '{"hero_eyebrow":"Products","hero_title":"Our","hero_highlight":"Products","hero_subtitle":"","hero_text":"High-quality rice mill machinery and material handling solutions designed for better productivity, durability and efficiency.","hero_image":"/images/hero-products.jpg","hero_side_text":"Complete Solutions\nfor Modern Rice Mills","hero_badges":[{"icon":"Settings","label":"Robust Design"},{"icon":"ShieldCheck","label":"Reliable Performance"},{"icon":"Cog","label":"Custom Solutions"},{"icon":"Leaf","label":"Energy Efficient"}],"help_title":"Need Help Choosing the Right Solution?","help_text":"Our experts will help you with the best equipment for your rice mill.","cta_title":"Looking for a Customized Solution?","cta_text":"We design and manufacture rice mill equipment as per your requirement."}'::jsonb);
  insert into public.site_content (key, value) values ('projects_page', '{"hero_eyebrow":"Projects","hero_title":"Our","hero_highlight":"Projects","hero_subtitle":"Real Solutions. Real Impact.","hero_text":"We have successfully designed, manufactured and installed rice mill blowers, bunkers, material handling and complete rice mill solutions across India. Each project reflects our commitment to quality, innovation and customer satisfaction.","hero_image":"/images/hero-projects.jpg","hero_side_text":"Powering Rice Mill\nSolutions Across India","hero_badges":[{"icon":"Settings","label":"Custom Engineered"},{"icon":"Users","label":"On-Time Delivery"},{"icon":"ShieldCheck","label":"Reliable Performance"},{"icon":"Leaf","label":"Serving Across India"}],"cta_title":"Ready to Start Your Project?","cta_text":"Let''s build a more productive future together."}'::jsonb);
  insert into public.site_content (key, value) values ('industries_page', '{"hero_eyebrow":"Industries","hero_title":"Powering Multiple Industries with","hero_highlight":"Rice Processing Solutions","hero_subtitle":"","hero_text":"Our innovative and reliable rice mill equipment supports a wide range of industries, helping them achieve higher efficiency, better product quality and sustainable growth.","hero_image":"/images/hero-industries.jpg","hero_side_text":"Stronger Industries\nA Brighter Tomorrow","hero_badges":[{"icon":"Settings","label":"Industry Focused Solutions"},{"icon":"ShieldCheck","label":"Reliable & Durable"},{"icon":"Leaf","label":"Energy Efficient"},{"icon":"Users","label":"Trusted by Businesses Across India"}],"section_eyebrow":"Industries We Serve","section_title":"Applications Across Diverse Industries","section_text":"From rice milling to food processing, animal feed, breweries and more — S.S.E Industries delivers customized equipment and complete solutions for various industries.","cta_title":"Let''s Build a Stronger Industry Together","cta_text":"Get the right rice mill equipment for your industry. Our team is ready to provide customized solutions.","cta_button":"Talk to Our Experts"}'::jsonb);
  insert into public.site_content (key, value) values ('services_page', '{"hero_eyebrow":"Services","hero_title":"Our","hero_highlight":"Services","hero_subtitle":"Complete Support for Your Rice Milling Success","hero_text":"At S.S.E Industries, we provide end-to-end services from design and manufacturing to installation and after-sales support. Our expert team ensures that you get the right rice mill solutions with maximum performance, minimum downtime and long-term value.","hero_image":"/images/hero-services.jpg","hero_side_text":"Your Partner in Every Step\nFrom Planning to Profitability","hero_badges":[{"icon":"Settings","label":"Expert Team"},{"icon":"Wrench","label":"End-to-End Solutions"},{"icon":"ShieldCheck","label":"Reliable Support"},{"icon":"Users","label":"Customer Satisfaction"}],"section_title":"Our Services","section_text":"Comprehensive services to keep your rice mill running at its best.","benefits":[{"icon":"Award","title":"Skilled & Experienced Team","text":"Industry experts with deep knowledge of rice mill systems."},{"icon":"Clock","title":"Timely Execution","text":"On-time delivery and project completion."},{"icon":"Settings","title":"Cost-Effective Solutions","text":"Maximum value with optimal investment."},{"icon":"Handshake","title":"Long-Term Partnership","text":"Continuous support for your business growth."}],"cta_title":"Need a Custom Solution?","cta_text":"Our experts are ready to discuss your requirements and provide the best solution.","cta_button":"Talk to Our Experts"}'::jsonb);
  insert into public.site_content (key, value) values ('clients_page', '{"hero_eyebrow":"Clients","hero_title":"Our","hero_highlight":"Clients","hero_subtitle":"Trusted by Rice Millers Across India","hero_text":"From small rice mills to large processing plants, our clients rely on S.S.E Industries for dependable machinery, timely execution and long-term support.","hero_image":"/images/prj-1.jpg","hero_side_text":"Trusted Partners\nAcross India","hero_badges":[{"icon":"Handshake","label":"Long-Term Partnerships"},{"icon":"MapPin","label":"Pan-India Presence"},{"icon":"ThumbsUp","label":"Satisfied Customers"},{"icon":"Headphones","label":"After-Sales Support"}],"clients_eyebrow":"Our Clients","clients_title":"Businesses That Trust Us","clients_text":"A few of the rice mills and agro industries we have had the privilege to work with.","testimonials_eyebrow":"Testimonials","testimonials_title":"What Our Clients Say","testimonials_text":"Real feedback from rice mill owners and plant managers we have worked with.","feedback_enabled":true,"feedback_title":"Share Your Experience","feedback_text":"Worked with us? We would love to hear from you. Your feedback is published after review.","cta_title":"Join Our Growing List of Happy Clients","cta_text":"Tell us about your rice mill project and get the right solution from our experts.","cta_button":"Get a Quote"}'::jsonb);
  insert into public.site_content (key, value) values ('gallery_page', '{"hero_eyebrow":"Gallery","hero_title":"Gallery","hero_highlight":"","hero_subtitle":"A Glimpse of Our Work","hero_text":"Explore our manufacturing facility, rice mill installations, equipment and project images. Each image reflects our commitment to quality, engineering excellence and customer success.","hero_image":"/images/plant-3.jpg","hero_side_text":"Real Projects\nReal Impact","hero_badges":[],"cta_title":"Have a Specific Requirement?","cta_text":"Our team can share more photos, videos and technical details based on your needs.","cta_button":"Request More Details"}'::jsonb);
  insert into public.site_content (key, value) values ('contact_page', '{"hero_eyebrow":"Contact","hero_title":"Contact","hero_highlight":"Us","hero_subtitle":"Let''s Build a More Productive Tomorrow","hero_text":"We are here to help you with rice mill equipment, custom solutions, project inquiries, service support and more. Get in touch with our team today.","hero_image":"/images/hero-contact.jpg","hero_side_text":"Your Trusted Partner\nin Rice Mill Solutions","hero_badges":[{"icon":"Headphones","label":"Quick Response"},{"icon":"Users","label":"Experienced Team"},{"icon":"Settings","label":"Customized Solutions"},{"icon":"Handshake","label":"Long-Term Partnership"}],"form_title":"Send Us a Message","enquiry_types":["Product Enquiry","Request a Quote","New Rice Mill Project","Modernization / Upgradation","Service & Maintenance","Spare Parts","Other"],"highlights":[{"icon":"Users","title":"Discuss Your Requirements","text":"Our experts understand your needs"},{"icon":"FileText","title":"Get Customized Solutions","text":"Tailor-made equipment and systems"},{"icon":"Settings","title":"On-Time Execution","text":"From design to installation"},{"icon":"Headphones","title":"Continuous Support","text":"We are with you even after project completion"}]}'::jsonb);
end if;
if not exists (select 1 from public.items) then
  insert into public.items (collection, data, sort_order, is_active) values ('hero_slides', '{"eyebrow":"S.S.E Industries","title":"Engineering the Future of","highlight":"Rice Processing","subtitle":"Manufacturers of Rice Mill Blowers, Bunkers, Erection & Complete Rice Mill Solutions","image":"/images/hero-home.jpg","btn1_text":"Get a Quote","btn1_link":"#quote","btn2_text":"Our Products","btn2_link":"/products"}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('hero_slides', '{"eyebrow":"Parboiling & Drying","title":"Complete Parboiling &","highlight":"Paddy Dryer Plants","subtitle":"Turnkey parboiling, drying and husk-fired furnace systems engineered for consistent grain quality","image":"/images/plant-3.jpg","btn1_text":"Get a Quote","btn1_link":"#quote","btn2_text":"View Projects","btn2_link":"/projects"}'::jsonb, 2, true);
  insert into public.items (collection, data, sort_order, is_active) values ('hero_slides', '{"eyebrow":"Built to Perform","title":"High-Performance","highlight":"Rice Mill Blowers","subtitle":"Energy-efficient blowers for paddy cleaning, husk handling and grain processing","image":"/images/p-blowers.jpg","btn1_text":"Enquire Now","btn1_link":"#quote","btn2_text":"View Details","btn2_link":"/products/rice-mill-blowers"}'::jsonb, 3, true);
  insert into public.items (collection, data, sort_order, is_active) values ('product_categories', '{"name":"Rice Mill Blowers","slug":"blowers"}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('product_categories', '{"name":"Rice Mill Bunkers & Hoppers","slug":"bunkers"}'::jsonb, 2, true);
  insert into public.items (collection, data, sort_order, is_active) values ('product_categories', '{"name":"Erection & Material Handling","slug":"material-handling"}'::jsonb, 3, true);
  insert into public.items (collection, data, sort_order, is_active) values ('product_categories', '{"name":"Customized Rice Mill Machinery","slug":"custom-machinery"}'::jsonb, 4, true);
  insert into public.items (collection, data, sort_order, is_active) values ('product_categories', '{"name":"Parboiling & Drying","slug":"parboiling-drying"}'::jsonb, 5, true);
  insert into public.items (collection, data, sort_order, is_active) values ('product_categories', '{"name":"Spare Parts & Accessories","slug":"spares"}'::jsonb, 6, true);
  insert into public.items (collection, data, sort_order, is_active) values ('products', '{"title":"Rice Mill Blowers","slug":"rice-mill-blowers","category":"blowers","featured":true,"image":"/images/p-blowers.jpg","images":["/images/gal-2.jpg","/images/gal-13.jpg"],"short_desc":"High performance blowers for paddy cleaning, husk handling and grain processing.","description":"Our rice mill blowers are engineered for continuous, heavy-duty operation in paddy cleaning, husk aspiration, husk conveying and grain processing lines. Dynamically balanced impellers, rigid casings and quality motors deliver high airflow with lower power consumption and minimal vibration.","features":["Dynamically balanced impellers for smooth operation","Energy-efficient design for lower power consumption","Heavy-duty MS / GI construction","Custom sizes as per airflow requirement","Low maintenance and long service life"],"specs":[{"label":"Application","value":"Paddy cleaning, husk handling, aspiration"},{"label":"Construction","value":"MS / GI / SS (as required)"},{"label":"Capacity","value":"Custom-built as per requirement"},{"label":"Drive","value":"Direct / belt driven"}]}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('products', '{"title":"Rice Mill Bunkers & Hoppers","slug":"rice-mill-bunkers-hoppers","category":"bunkers","featured":true,"image":"/images/p-bunkers.jpg","images":["/images/gal-3.jpg","/images/svc-2.jpg"],"short_desc":"Strong and reliable storage solutions for continuous and efficient operation.","description":"Robust storage bunkers and hoppers designed for smooth grain flow and continuous plant operation. Fabricated with precision for paddy, rice, broken rice and bran storage, with discharge designs that prevent bridging and choking.","features":["Smooth discharge design prevents choking","Strong structural frame for long life","Modular panels for easy erection","Capacities as per plant layout"],"specs":[{"label":"Material","value":"GI / MS sheets"},{"label":"Use","value":"Paddy, rice, broken & bran storage"},{"label":"Capacity","value":"As per requirement"}]}'::jsonb, 2, true);
  insert into public.items (collection, data, sort_order, is_active) values ('products', '{"title":"Erection & Material Handling","slug":"erection-material-handling","category":"material-handling","featured":true,"image":"/images/p-erection.jpg","images":["/images/gal-4.jpg","/images/gal-12.jpg"],"short_desc":"Complete erection, conveyors and material handling systems for rice mills.","description":"Complete erection services along with elevators, conveyors, chutes and structural work for rice mills. Our team plans the layout, fabricates and installs the entire material handling system for a smooth, efficient flow from intake to packing.","features":["Complete plant layout and erection","Elevators, conveyors, chutes and structures","Experienced on-site erection team","Safe, timely installation"],"specs":[{"label":"Scope","value":"Design, fabrication & erection"},{"label":"Coverage","value":"Pan-India"}]}'::jsonb, 3, true);
  insert into public.items (collection, data, sort_order, is_active) values ('products', '{"title":"Customized Rice Mill Machinery","slug":"customized-rice-mill-machinery","category":"custom-machinery","featured":true,"image":"/images/p-custom.jpg","images":["/images/gal-6.jpg","/images/gal-11.jpg"],"short_desc":"Tailor-made solutions designed for your unique requirements.","description":"Every rice mill is different. We design and build customized machinery and complete lines to match your capacity, space and process requirements — from small rice mills to large processing plants.","features":["Designed around your capacity and layout","Precision fabrication","Integration with existing machinery","Complete commissioning support"],"specs":[{"label":"Capacity","value":"Small to large TPD plants"},{"label":"Design","value":"As per client requirement"}]}'::jsonb, 4, true);
  insert into public.items (collection, data, sort_order, is_active) values ('products', '{"title":"Belt Conveyors","slug":"belt-conveyors","category":"material-handling","image":"/images/p-belt.jpg","images":["/images/gal-5.jpg"],"short_desc":"Efficient conveying systems for smooth material flow.","description":"Belt conveyors built for smooth and reliable horizontal and inclined transport of paddy, rice and by-products with minimal spillage and breakage.","features":["Low grain breakage","Horizontal and inclined configurations","Quality belts, rollers and drives"],"specs":[{"label":"Length","value":"As per layout"},{"label":"Belt width","value":"As per capacity"}]}'::jsonb, 5, true);
  insert into public.items (collection, data, sort_order, is_active) values ('products', '{"title":"Bucket Elevators","slug":"bucket-elevators","category":"material-handling","image":"/images/p-bucket.jpg","images":[],"short_desc":"Reliable vertical conveying solutions for grains and husk.","description":"Bucket elevators for dependable vertical conveying of paddy, rice and husk. Designed for gentle handling, high uptime and easy maintenance.","features":["Gentle handling of grain","Rigid casing and quality buckets","Easy inspection and maintenance doors"],"specs":[{"label":"Height","value":"As per plant layout"},{"label":"Capacity","value":"As per requirement"}]}'::jsonb, 6, true);
  insert into public.items (collection, data, sort_order, is_active) values ('products', '{"title":"Dust Collection Systems","slug":"dust-collection-systems","category":"custom-machinery","image":"/images/p-dust.jpg","images":["/images/gal-7.jpg"],"short_desc":"Cleaner operation with efficient dust control systems.","description":"Cyclones, ducting and dust collection systems that keep your plant clean and safe, improve working conditions and protect machinery.","features":["Cyclone separators and ducting","Improves workplace hygiene and safety","Designed for your plant airflow"],"specs":[{"label":"Type","value":"Cyclone / bag filter (as required)"}]}'::jsonb, 7, true);
  insert into public.items (collection, data, sort_order, is_active) values ('products', '{"title":"Paddy Dryer & Parboiling Plant","slug":"paddy-dryer-parboiling-plant","category":"parboiling-drying","image":"/images/plant-2.jpg","images":["/images/plant-1.jpg","/images/plant-3.jpg","/images/plant-6.jpg"],"short_desc":"Complete paddy drying and parboiling systems for uniform, quality output.","description":"Column dryers, soaking tanks, steaming and parboiling plants engineered for uniform drying and consistent grain quality, supplied with elevators, bunkers and structures as a complete package.","features":["Uniform drying and consistent quality","Complete plant including elevators and structure","Integration with husk-fired furnace"],"specs":[{"label":"Capacity","value":"As per requirement"},{"label":"Heating","value":"Husk fired furnace / boiler"}]}'::jsonb, 8, true);
  insert into public.items (collection, data, sort_order, is_active) values ('products', '{"title":"Husk Fired Furnace","slug":"husk-fired-furnace","category":"parboiling-drying","image":"/images/husk-furnace.jpg","images":["/images/plant-4.jpg"],"short_desc":"Efficient husk furnaces providing clean hot air for paddy drying.","description":"Husk fired furnaces that use rice husk as fuel to generate hot air for paddy dryers — reducing fuel cost and making effective use of mill by-products.","features":["Uses rice husk as fuel","Lower drying cost","Robust construction for continuous operation"],"specs":[{"label":"Fuel","value":"Rice husk"},{"label":"Application","value":"Paddy dryers"}]}'::jsonb, 9, true);
  insert into public.items (collection, data, sort_order, is_active) values ('products', '{"title":"Spare Parts & Accessories","slug":"spare-parts-accessories","category":"spares","image":"/images/p-spares.jpg","images":["/images/gal-10.jpg"],"short_desc":"Genuine spare parts for long-lasting performance.","description":"Genuine spare parts and accessories for rice mill machinery — bearings, pulleys, belts, buckets and more — to keep your plant running without interruption.","features":["Genuine quality parts","Quick availability","Guidance for right part selection"],"specs":[{"label":"Range","value":"Bearings, pulleys, belts, buckets & more"}]}'::jsonb, 10, true);
  insert into public.items (collection, data, sort_order, is_active) values ('project_categories', '{"name":"Rice Mill Plants","slug":"rice-mill-plants"}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('project_categories', '{"name":"Blowers Installation","slug":"blowers"}'::jsonb, 2, true);
  insert into public.items (collection, data, sort_order, is_active) values ('project_categories', '{"name":"Bunkers & Hoppers","slug":"bunkers"}'::jsonb, 3, true);
  insert into public.items (collection, data, sort_order, is_active) values ('project_categories', '{"name":"Erection & Material Handling","slug":"material-handling"}'::jsonb, 4, true);
  insert into public.items (collection, data, sort_order, is_active) values ('project_categories', '{"name":"Modernization & Upgradation","slug":"modernization"}'::jsonb, 5, true);
  insert into public.items (collection, data, sort_order, is_active) values ('project_categories', '{"name":"Custom Projects","slug":"custom"}'::jsonb, 6, true);
  insert into public.items (collection, data, sort_order, is_active) values ('projects', '{"title":"100 TPD Rice Mill Plant","slug":"100-tpd-rice-mill-plant","category":"rice-mill-plants","location":"Andhra Pradesh, India","featured":true,"image":"/images/prj-1.jpg","images":["/images/gal-1.jpg"],"short_desc":"Complete solution including blowers, bunkers, material handling and installation.","description":"Complete solution including blowers, bunkers, material handling and installation for a 100 TPD rice mill plant."}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('projects', '{"title":"60 TPD Rice Mill Plant","slug":"60-tpd-rice-mill-plant","category":"rice-mill-plants","location":"Karnataka, India","featured":true,"image":"/images/prj-2.jpg","images":["/images/gal-11.jpg"],"short_desc":"Design, manufacturing and erection of complete rice mill with conveyors.","description":"Design, manufacturing and erection of a complete 60 TPD rice mill with conveyors."}'::jsonb, 2, true);
  insert into public.items (collection, data, sort_order, is_active) values ('projects', '{"title":"Bunker & Hopper System","slug":"bunker-hopper-system","category":"bunkers","location":"Telangana, India","featured":true,"image":"/images/prj-3.jpg","images":["/images/gal-3.jpg"],"short_desc":"Fabrication and installation of storage bunkers for continuous operation.","description":"Fabrication and installation of storage bunkers for continuous operation."}'::jsonb, 3, true);
  insert into public.items (collection, data, sort_order, is_active) values ('projects', '{"title":"Blower System Installation","slug":"blower-system-installation","category":"blowers","location":"Tamil Nadu, India","featured":true,"image":"/images/prj-4.jpg","images":["/images/gal-2.jpg"],"short_desc":"High efficiency blowers for paddy cleaning and husk handling.","description":"High efficiency blowers for paddy cleaning and husk handling."}'::jsonb, 4, true);
  insert into public.items (collection, data, sort_order, is_active) values ('projects', '{"title":"Material Handling & Conveyors","slug":"material-handling-conveyors","category":"material-handling","location":"Maharashtra, India","image":"/images/prj-5.jpg","images":["/images/gal-5.jpg"],"short_desc":"Custom conveying systems for smooth material flow.","description":"Custom conveying systems for smooth material flow."}'::jsonb, 5, true);
  insert into public.items (collection, data, sort_order, is_active) values ('projects', '{"title":"Rice Mill Modernization","slug":"rice-mill-modernization","category":"modernization","location":"Chhattisgarh, India","image":"/images/prj-6.jpg","images":[],"short_desc":"Upgradation with latest technology for higher output and efficiency.","description":"Upgradation with latest technology for higher output and efficiency."}'::jsonb, 6, true);
  insert into public.items (collection, data, sort_order, is_active) values ('projects', '{"title":"Dust Collection System","slug":"dust-collection-system","category":"custom","location":"Punjab, India","image":"/images/prj-7.jpg","images":["/images/gal-7.jpg"],"short_desc":"Complete dust control solution for a cleaner and safer workplace.","description":"Complete dust control solution for a cleaner and safer workplace."}'::jsonb, 7, true);
  insert into public.items (collection, data, sort_order, is_active) values ('projects', '{"title":"Customized Solution","slug":"customized-solution","category":"custom","location":"Odisha, India","image":"/images/prj-8.jpg","images":[],"short_desc":"Tailor-made rice mill machinery as per client requirements.","description":"Tailor-made rice mill machinery as per client requirements."}'::jsonb, 8, true);
  insert into public.items (collection, data, sort_order, is_active) values ('industries', '{"title":"Rice Mills","slug":"rice-mills","featured":true,"image":"/images/ind-1.jpg","short_desc":"Complete rice milling solutions from paddy cleaning to final packing."}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('industries', '{"title":"Parboiling Plants","slug":"parboiling-plants","featured":true,"image":"/images/ind-6.jpg","short_desc":"Efficient systems for parboiling and drying operations."}'::jsonb, 2, true);
  insert into public.items (collection, data, sort_order, is_active) values ('industries', '{"title":"Grain Processing","slug":"grain-processing","featured":true,"image":"/images/ind-2.jpg","short_desc":"Handling and processing of various grains like wheat, maize, millets, etc."}'::jsonb, 3, true);
  insert into public.items (collection, data, sort_order, is_active) values ('industries', '{"title":"Agro & Allied Industries","slug":"agro-allied","featured":true,"image":"/images/ind-8.jpg","short_desc":"Rice and grain handling solutions for agro-based industries."}'::jsonb, 4, true);
  insert into public.items (collection, data, sort_order, is_active) values ('industries', '{"title":"Animal Feed Industry","slug":"animal-feed","image":"/images/ind-3.jpg","short_desc":"Material handling systems for feed manufacturing plants."}'::jsonb, 5, true);
  insert into public.items (collection, data, sort_order, is_active) values ('industries', '{"title":"Breweries & Malt Industry","slug":"breweries-malt","image":"/images/ind-4.jpg","short_desc":"Conveying, storage and handling solutions for malt and grains."}'::jsonb, 6, true);
  insert into public.items (collection, data, sort_order, is_active) values ('industries', '{"title":"Food Processing Industry","slug":"food-processing","image":"/images/ind-5.jpg","short_desc":"Customized material handling solutions for food processing units."}'::jsonb, 7, true);
  insert into public.items (collection, data, sort_order, is_active) values ('industries', '{"title":"Seed Processing Industry","slug":"seed-processing","image":"/images/ind-7.jpg","short_desc":"Cleaning, grading and handling equipment for seed plants."}'::jsonb, 8, true);
  insert into public.items (collection, data, sort_order, is_active) values ('industries', '{"title":"Flour & Starch Industry","slug":"flour-starch","image":"/images/ind-9.jpg","short_desc":"Pneumatic and mechanical conveying systems for flour and starch."}'::jsonb, 9, true);
  insert into public.items (collection, data, sort_order, is_active) values ('industries', '{"title":"Custom Projects","slug":"custom-projects","image":"/images/ind-10.jpg","short_desc":"Tailor-made solutions for unique industry requirements."}'::jsonb, 10, true);
  insert into public.items (collection, data, sort_order, is_active) values ('services', '{"title":"Consultation & Planning","slug":"consultation-planning","icon":"ClipboardList","image":"/images/svc-1.jpg","short_desc":"Understanding your requirements and recommending the right solutions.","description":"We start by understanding your capacity, space, budget and process goals, then recommend the right machinery and layout for your rice mill.","features":["Site study and requirement analysis","Capacity and layout planning","Right equipment recommendation"]}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('services', '{"title":"Design & Engineering","slug":"design-engineering","icon":"Settings","image":"/images/svc-2.jpg","short_desc":"Customized design for rice mill blowers, bunkers, material handling and complete plants.","description":"Our engineering team prepares customized designs for blowers, bunkers, material handling and complete plants with precision.","features":["Custom plant layouts","Equipment design","Structural engineering"]}'::jsonb, 2, true);
  insert into public.items (collection, data, sort_order, is_active) values ('services', '{"title":"Manufacturing","slug":"manufacturing","icon":"Factory","image":"/images/svc-3.jpg","short_desc":"High-quality, durable equipment manufactured with precision and advanced technology.","description":"Equipment is fabricated at our facility using quality raw materials, precision processes and strict quality checks.","features":["Quality raw materials","Precision fabrication","Quality inspection"]}'::jsonb, 3, true);
  insert into public.items (collection, data, sort_order, is_active) values ('services', '{"title":"Installation & Commissioning","slug":"installation-commissioning","icon":"Wrench","image":"/images/svc-4.jpg","short_desc":"Professional installation and commissioning to ensure smooth operations.","description":"Our experienced erection team installs and commissions your equipment on site, ensuring everything runs smoothly from day one.","features":["Experienced erection team","Trial runs and commissioning","Operator guidance"]}'::jsonb, 4, true);
  insert into public.items (collection, data, sort_order, is_active) values ('services', '{"title":"Maintenance & Support","slug":"maintenance-support","icon":"Headphones","image":"/images/svc-5.jpg","short_desc":"Preventive maintenance, troubleshooting and annual service support.","description":"Preventive maintenance, troubleshooting and annual service support to minimize downtime and extend equipment life.","features":["Preventive maintenance","Breakdown support","Annual maintenance contracts"]}'::jsonb, 5, true);
  insert into public.items (collection, data, sort_order, is_active) values ('services', '{"title":"Spare Parts Supply","slug":"spare-parts-supply","icon":"Package","image":"/images/svc-6.jpg","short_desc":"Genuine spare parts for long-lasting and uninterrupted performance.","description":"Genuine spare parts supplied quickly to keep your plant running without interruption.","features":["Genuine parts","Quick dispatch","Right part guidance"]}'::jsonb, 6, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery_categories', '{"name":"Rice Mill Plants","slug":"rice-mill-plants"}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery_categories', '{"name":"Parboiling & Dryers","slug":"parboiling"}'::jsonb, 2, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery_categories', '{"name":"Blowers","slug":"blowers"}'::jsonb, 3, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery_categories', '{"name":"Bunkers & Hoppers","slug":"bunkers"}'::jsonb, 4, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery_categories', '{"name":"Erection & Installation","slug":"erection"}'::jsonb, 5, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery_categories', '{"name":"Material Handling","slug":"material-handling"}'::jsonb, 6, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery_categories', '{"name":"Manufacturing Facility","slug":"facility"}'::jsonb, 7, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery_categories', '{"name":"Spare Parts","slug":"spares"}'::jsonb, 8, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Parboiling & Dryer Plant","category":"parboiling","image":"/images/plant-1.jpg"}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Paddy Dryer Tower","category":"parboiling","image":"/images/plant-2.jpg"}'::jsonb, 2, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Complete Parboiling Plant","category":"parboiling","image":"/images/plant-3.jpg"}'::jsonb, 3, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Dryer with Husk Furnace","category":"parboiling","image":"/images/plant-4.jpg"}'::jsonb, 4, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Dryer Plant Installation","category":"erection","image":"/images/plant-5.jpg"}'::jsonb, 5, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Parboiling Unit","category":"parboiling","image":"/images/plant-6.jpg"}'::jsonb, 6, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"100 TPD Rice Mill Plant","category":"rice-mill-plants","image":"/images/gal-1.jpg"}'::jsonb, 7, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Rice Mill Blower","category":"blowers","image":"/images/gal-2.jpg"}'::jsonb, 8, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Storage Bunker","category":"bunkers","image":"/images/gal-3.jpg"}'::jsonb, 9, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Erection & Installation","category":"erection","image":"/images/gal-4.jpg"}'::jsonb, 10, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Belt Conveyor System","category":"material-handling","image":"/images/gal-5.jpg"}'::jsonb, 11, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Rice Mill Machinery Line","category":"rice-mill-plants","image":"/images/gal-6.jpg"}'::jsonb, 12, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Dust Collection System","category":"material-handling","image":"/images/gal-7.jpg"}'::jsonb, 13, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Project Installation","category":"erection","image":"/images/gal-8.jpg"}'::jsonb, 14, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Manufacturing Facility","category":"facility","image":"/images/gal-9.jpg"}'::jsonb, 15, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Spare Parts & Accessories","category":"spares","image":"/images/gal-10.jpg"}'::jsonb, 16, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"60 TPD Rice Mill Project","category":"rice-mill-plants","image":"/images/gal-11.jpg"}'::jsonb, 17, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Material Handling System","category":"material-handling","image":"/images/gal-12.jpg"}'::jsonb, 18, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Fan & Ducting","category":"blowers","image":"/images/gal-13.jpg"}'::jsonb, 19, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Custom Fabrication","category":"facility","image":"/images/gal-14.jpg"}'::jsonb, 20, true);
  insert into public.items (collection, data, sort_order, is_active) values ('gallery', '{"title":"Completed Project","category":"rice-mill-plants","image":"/images/gal-15.jpg"}'::jsonb, 21, true);
  insert into public.items (collection, data, sort_order, is_active) values ('testimonials', '{"name":"Rice Mill Owner","designation":"Owner","company":"","location":"Andhra Pradesh","project":"100 TPD Rice Mill Plant","message":"S.S.E Industries delivered our 100 TPD rice mill project on time with excellent quality. Their support and service are outstanding.","rating":5,"photo":"","video_url":"","featured":true}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('clients', '{"name":"Sample Client – Rice Mill","location":"Andhra Pradesh","industry":"Rice Mill","logo":"","website":"","project":"100 TPD Rice Mill Plant","featured":true}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('clients', '{"name":"Sample Client – Parboiling Unit","location":"Karnataka","industry":"Parboiling Plant","logo":"","website":"","project":"Paddy Dryer & Parboiling Plant","featured":true}'::jsonb, 2, true);
  insert into public.items (collection, data, sort_order, is_active) values ('clients', '{"name":"Sample Client – Agro Industry","location":"Telangana","industry":"Agro & Allied","logo":"","website":"","project":"Bunker & Hopper System","featured":true}'::jsonb, 3, true);
  insert into public.items (collection, data, sort_order, is_active) values ('faqs', '{"question":"Do you manufacture equipment as per our requirement?","answer":"Yes. We design and fabricate blowers, bunkers, material handling systems and complete plants customized to your capacity, layout and process."}'::jsonb, 1, true);
  insert into public.items (collection, data, sort_order, is_active) values ('faqs', '{"question":"Do you provide installation and commissioning?","answer":"Yes. Our experienced erection team handles on-site installation, trial runs and commissioning across India."}'::jsonb, 2, true);
  insert into public.items (collection, data, sort_order, is_active) values ('faqs', '{"question":"Can you modernize or upgrade an existing rice mill?","answer":"Yes. We study your current setup and recommend upgrades that improve output, efficiency and reliability."}'::jsonb, 3, true);
  insert into public.items (collection, data, sort_order, is_active) values ('faqs', '{"question":"Do you supply spare parts and after-sales service?","answer":"Yes. We supply genuine spare parts and offer preventive maintenance, troubleshooting and annual service support."}'::jsonb, 4, true);
  insert into public.items (collection, data, sort_order, is_active) values ('faqs', '{"question":"How do I get a quotation?","answer":"Use the \"Get a Quote\" button, fill the contact form, or message us on WhatsApp with your requirement. Our team will get back to you quickly."}'::jsonb, 5, true);
end if;
end $$;

-- 6. YOUR SUPER ADMIN ---------------------------------------------------
-- Change this email to the one you will log in with, then create the same
-- user in Supabase → Authentication → Users → "Add user" (with a password).
insert into public.admin_users (email, role) values ('admin@sseindustries.in', 'super_admin')
on conflict (email) do update set role = 'super_admin';
